(()=>{"use strict";
const Q=new URLSearchParams(location.search),sid=(Q.get("id")||"").trim(),group=(Q.get("group")||"").trim().toUpperCase(),token=(Q.get("token")||"").trim(),valid=sid&&["A","B","C"].includes(group)&&token,$=id=>document.getElementById(id);
let task=0,stage=0,responses=[],started=0,finalized=false,marksA=[],marksL=[],marksG=[],stateA=null,stateL=null,stateG=null;
$("studyMeta").textContent=STUDY_CONFIG.studyName;if(STUDY_CONFIG.requireAssignedLink&&!valid)$("invalid").hidden=false;else{$("consent").hidden=false;$("showId").textContent=sid;$("showGroup").textContent=group}
function sample(poly,n=61){let lens=[],cum=[0],tot=0;for(let i=0;i<poly.length;i++){let a=poly[i],b=poly[(i+1)%poly.length],l=Math.hypot(b[0]-a[0],b[1]-a[1]);lens.push(l);tot+=l;cum.push(tot)}let pts=[],ss=[];for(let k=0;k<n;k++){let s=tot*k/n,j=0;while(j<poly.length-1&&s>=cum[j+1])j++;let t=(s-cum[j])/lens[j],a=poly[j],b=poly[(j+1)%poly.length];pts.push([a[0]+t*(b[0]-a[0]),a[1]+t*(b[1]-a[1])]);ss.push(k/n)}return[pts,ss]}
function data(i){let p=STUDY_TASKS.polygons[i],r=STUDY_TASKS.refs[i],[pts,s]=sample(p),L=r[0],G=r[1],dl=pts.map(q=>Math.hypot(q[0]-L[0],q[1]-L[1])),dg=pts.map(q=>Math.hypot(q[0]-G[0],q[1]-G[1])),d1=a=>a.slice(1).map((v,k)=>v-a[k]),ad=a=>d1(a).map(Math.abs);return{s,dl,dg,d1l:d1(dl),d1g:d1(dg),cl:ad(d1(dl)),cg:ad(d1(dg))}}
function base(id){let c=$(id),x=c.getContext("2d");x.clearRect(0,0,c.width,c.height);x.font="17px system-ui";x.strokeStyle="#111";x.fillStyle="#111";return[c,x]}
function metrics(p){let lens=[],cum=[0],total=0;for(let i=0;i<p.length;i++){let a=p[i],b=p[(i+1)%p.length],l=Math.hypot(b[0]-a[0],b[1]-a[1]);lens.push(l);total+=l;cum.push(total)}return{lens,cum,total}}
function drawA(){let p=STUDY_TASKS.polygons[task],[c,x]=base("plotA"),xs=p.map(q=>q[0]),ys=p.map(q=>q[1]),mnx=Math.min(...xs),mxx=Math.max(...xs),mny=Math.min(...ys),mxy=Math.max(...ys),X=v=>100+(v-mnx)/(mxx-mnx)*780,Y=v=>380-(v-mny)/(mxy-mny)*300,cp=p.map(q=>[X(q[0]),Y(q[1])]);x.lineWidth=4;x.beginPath();cp.forEach((q,i)=>i?x.lineTo(q[0],q[1]):x.moveTo(q[0],q[1]));x.closePath();x.stroke();for(const q of cp){x.beginPath();x.arc(q[0],q[1],5,0,2*Math.PI);x.fill()}stateA={cp,m:metrics(p)};drawMarksA()}
function drawGraph(id,v,title,ch){let[c,x]=base(id),lo0=Math.min(...v),hi0=Math.max(...v),pad=Math.max((hi0-lo0)*.08,.02),lo=lo0-pad,hi=hi0+pad,left=90,right=910,top=45,bottom=295,X=i=>left+i/(v.length-1)*(right-left),Y=y=>bottom-(y-lo)/(hi-lo)*(bottom-top);x.beginPath();x.moveTo(left-15,top-10);x.lineTo(left-15,bottom);x.lineTo(right+20,bottom);x.stroke();for(const f of[0,.25,.5,.75,1])x.fillText(f.toFixed(2),left+f*(right-left)-18,330);x.beginPath();v.forEach((y,i)=>i?x.lineTo(X(i),Y(y)):x.moveTo(X(i),Y(y)));x.stroke();x.fillText(title,760,30);x.fillText("normalized journey position s",365,350);let st={left,right,top,bottom};if(ch==="L")stateL=st;else stateG=st;drawMarks(ch)}
function drawMarksA(){let x=$("plotA").getContext("2d");x.save();x.font="bold 17px system-ui";marksA.forEach((m,i)=>{x.fillStyle="#1f5fbf";x.beginPath();x.arc(m.px,m.py,9,0,2*Math.PI);x.fill();x.fillStyle="#fff";x.textAlign="center";x.textBaseline="middle";x.fillText(String(i+1),m.px,m.py+1)});x.restore();summary()}
function drawMarks(ch){let st=ch==="L"?stateL:stateG,arr=ch==="L"?marksL:marksG,id=ch==="L"?"plotL":"plotG",x=$(id).getContext("2d");x.save();x.font="bold 17px system-ui";arr.forEach((m,i)=>{let px=st.left+m.s*(st.right-st.left);x.strokeStyle="#1f5fbf";x.setLineDash([7,6]);x.lineWidth=2;x.beginPath();x.moveTo(px,st.top);x.lineTo(px,st.bottom);x.stroke();x.setLineDash([]);x.fillStyle="#1f5fbf";x.fillText(String(i+1),px+5,st.top+20)});x.restore();summary()}
function summary(){$("countA").textContent=marksA.length;$("selectedA").textContent=marksA.length?marksA.map(m=>m.s.toFixed(3)).join(", "):"None";$("countL").textContent=marksL.length;$("selectedL").textContent=marksL.length?marksL.map(m=>m.s.toFixed(3)).join(", "):"None";$("countG").textContent=marksG.length;$("selectedG").textContent=marksG.length?marksG.map(m=>m.s.toFixed(3)).join(", "):"None"}
function nearSeg(px,py,a,b){let vx=b[0]-a[0],vy=b[1]-a[1],wx=px-a[0],wy=py-a[1],den=vx*vx+vy*vy,t=den?(wx*vx+wy*vy)/den:0;t=Math.max(0,Math.min(1,t));let qx=a[0]+t*vx,qy=a[1]+t*vy;return{t,qx,qy,d2:(px-qx)**2+(py-qy)**2}}
function markA(px,py){let best=null;for(let i=0;i<stateA.cp.length;i++){let c=nearSeg(px,py,stateA.cp[i],stateA.cp[(i+1)%stateA.cp.length]);if(!best||c.d2<best.d2)best={...c,edge:i}}let s=(stateA.m.cum[best.edge]+best.t*stateA.m.lens[best.edge])/stateA.m.total;return{s:s>=1?0:s,px:best.qx,py:best.qy,rawX:px,rawY:py}}
function markG(px,py,st){if(px<st.left||px>st.right||py<st.top-20||py>st.bottom+20)return null;return{s:Math.max(0,Math.min(1,(px-st.left)/(st.right-st.left))),rawX:px,rawY:py}}
function pos(e,id){let c=$(id),r=c.getBoundingClientRect();return[(e.clientX-r.left)*c.width/r.width,(e.clientY-r.top)*c.height/r.height]}
function handle(id,ch){$(id).addEventListener("click",e=>{if($("insufficient").checked)return;let[px,py]=pos(e,id),arr=ch==="A"?marksA:ch==="L"?marksL:marksG;if(arr.length>=STUDY_CONFIG.maxMarksPerChannel)return;let m=ch==="A"?markA(px,py):markG(px,py,ch==="L"?stateL:stateG);if(!m)return;let j=arr.findIndex(q=>Math.abs(q.s-m.s)<.018);if(j>=0)arr.splice(j,1);else arr.push(m);arr.sort((a,b)=>a.s-b.s);renderStim()})}
handle("plotA","A");handle("plotL","L");handle("plotG","G");
[["undoA",marksA],["undoL",marksL],["undoG",marksG]].forEach(()=>{});$("undoA").onclick=()=>{marksA.pop();renderStim()};$("clearA").onclick=()=>{marksA=[];renderStim()};$("undoL").onclick=()=>{marksL.pop();renderStim()};$("clearL").onclick=()=>{marksL=[];renderStim()};$("undoG").onclick=()=>{marksG.pop();renderStim()};$("clearG").onclick=()=>{marksG=[];renderStim()};
$("insufficient").onchange=()=>{if($("insufficient").checked){marksA=[];marksL=[];marksG=[];renderStim()}for(const id of["plotA","plotL","plotG"]){$(id).style.opacity=$("insufficient").checked?".55":"1";$(id).style.cursor=$("insufficient").checked?"not-allowed":"crosshair"}}
function evidence(){if(group==="A")return[["VISIBLE_CHANGE","Visible change where two straight segments meet"],["OVERALL_SHAPE","Overall shape structure"],["VISIBLE_JUNCTIONS","Number of visible junctions"],["COMBINATION","Combination of these"],["INSUFFICIENT","Insufficient evidence"]];if(group==="B"||(group==="C"&&stage===0))return[["L_ONLY","Mainly L-channel pattern"],["G_ONLY","Mainly G-channel pattern"],["BOTH_CHANNELS","Both L and G channels"],["OVERALL_PAIR","Overall comparison of the two channels"],["INSUFFICIENT","Insufficient evidence"]];if(group==="C"&&stage===1)return[["L_FIRST","Mainly L first-change graph"],["G_FIRST","Mainly G first-change graph"],["BOTH_FIRST","Both first-change graphs"],["OVERALL_FIRST","Overall comparison of both first-change graphs"],["INSUFFICIENT","Insufficient evidence"]];return[["L_CHANGE","Mainly L change-in-change graph"],["G_CHANGE","Mainly G change-in-change graph"],["BOTH_CHANGE","Both change-in-change graphs"],["ALL_REP","Combination of representations"],["INSUFFICIENT","Insufficient evidence"]]}
function drawEvidence(){let b=$("evidenceOptions");b.innerHTML="";for(const[v,l]of evidence()){let q=document.createElement("label");q.innerHTML=`<input type="radio" name="evidence" value="${v}"> ${l}`;b.appendChild(q)}}
function extra(){let b=$("stageExtra");b.innerHTML="";if(group==="C"&&stage===2)b.innerHTML='<fieldset><legend>Which representation was most useful?</legend><div class="radiolist"><label><input type="radio" name="mostUseful" value="Raw distances">Raw distances</label><label><input type="radio" name="mostUseful" value="First changes">First changes</label><label><input type="radio" name="mostUseful" value="Change-in-change">Change-in-change</label><label><input type="radio" name="mostUseful" value="Combination">Combination</label></div></fieldset>'}
function series(){let d=data(task);if(group==="B"||(group==="C"&&stage===0))return{L:d.dl,G:d.dg,tL:"D_L(s)",tG:"D_G(s)",dL:"Distance history from reference L",dG:"Distance history from reference G"};if(group==="C"&&stage===1)return{L:d.d1l,G:d.d1g,tL:"dD_L",tG:"dD_G",dL:"First changes in L-distance",dG:"First changes in G-distance"};return{L:d.cl,G:d.cg,tL:"C_L",tG:"C_G",dL:"Change-in-change for L",dG:"Change-in-change for G"}}
function render(){marksA=[];marksL=[];marksG=[];$("insufficient").checked=false;drawEvidence();extra();renderStim();started=performance.now()}
function renderStim(){let total=group==="C"?18:6,current=group==="C"?task*3+stage+1:task+1;$("progress").textContent=`Screen ${current} of ${total}`;if(group==="A"){$("singleStimulus").hidden=false;$("dualStimulus").hidden=true;$("heading").textContent=`Task A${task+1}`;$("instruction").textContent="Inspect the visible closed boundary.";drawA()}else{$("singleStimulus").hidden=true;$("dualStimulus").hidden=false;let names=["Raw distance histories","First changes","Change in the changes"],s=series();$("heading").textContent=group==="B"?`Task B${task+1}`:`Task C${task+1} — Stage ${stage+1}: ${names[stage]}`;$("instruction").textContent="The boundary is hidden. Mark transition evidence separately on the L and G channel graphs.";$("titleL").textContent=s.tL;$("titleG").textContent=s.tG;$("descL").textContent=s.dL;$("descG").textContent=s.dG;drawGraph("plotL",s.L,s.tL,"L");drawGraph("plotG",s.G,s.tG,"G")}summary()}
function checked(n){return document.querySelector(`input[name="${n}"]:checked`)?.value||""}
function reset(){marksA=[];marksL=[];marksG=[];$("nseg").value="";document.querySelectorAll('input[name="confidence"],input[name="evidence"],input[name="mostUseful"]').forEach(x=>x.checked=false);$("status").textContent=""}
function validForm(){let ins=$("insufficient").checked;if(!$("nseg").value.trim()||!checked("confidence")||!checked("evidence")){ $("status").textContent="Please complete segment count, confidence, and evidence choice.";return false}if(group==="A"&&!ins&&!marksA.length){$("status").textContent="Mark at least one transition, or select insufficient evidence.";return false}if(group!=="A"&&!ins&&!marksL.length&&!marksG.length){$("status").textContent="Mark at least one L or G transition location, or select insufficient evidence.";return false}if(group==="C"&&stage===2&&!checked("mostUseful")){ $("status").textContent="Please select the most useful representation.";return false}return true}
async function send(r){if(!STUDY_CONFIG.submitEndpoint)return;try{await fetch(STUDY_CONFIG.submitEndpoint,{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(r)})}catch(e){}}
$("startBtn").onclick=()=>{if(!$("ready").checked)return alert("Please confirm that you are ready.");$("consent").hidden=true;$("study").hidden=false;render()};
$("nextBtn").onclick=async()=>{if(finalized||!validForm())return;$("nextBtn").disabled=true;let rec={study_id:sid,group,token,task:task+1,stage:group==="C"?stage+1:1,marked_count_A:marksA.length,marked_s_A:marksA.map(m=>m.s.toFixed(5)).join(","),raw_clicks_A:marksA.map(m=>`${Math.round(m.rawX)}:${Math.round(m.rawY)}`).join("|"),marked_count_L:marksL.length,marked_s_L:marksL.map(m=>m.s.toFixed(5)).join(","),raw_clicks_L:marksL.map(m=>`${Math.round(m.rawX)}:${Math.round(m.rawY)}`).join("|"),marked_count_G:marksG.length,marked_s_G:marksG.map(m=>m.s.toFixed(5)).join(","),raw_clicks_G:marksG.map(m=>`${Math.round(m.rawX)}:${Math.round(m.rawY)}`).join("|"),predicted_segments:Number($("nseg").value),confidence:Number(checked("confidence")),evidence_code:checked("evidence"),insufficient_evidence:$("insufficient").checked,most_useful:checked("mostUseful"),stage_duration_ms:Math.round(performance.now()-started),submitted_at:new Date().toISOString(),user_agent:navigator.userAgent};responses.push(rec);localStorage.setItem("study_"+token,JSON.stringify(responses));await send(rec);reset();if(group==="C"&&stage<2){stage++;render();$("nextBtn").disabled=false;return}stage=0;task++;if(task<6){render();$("nextBtn").disabled=false;return}finalized=true;$("study").hidden=true;$("done").hidden=false;$("serverStatus").textContent="Responses submitted. Keep the CSV backup until receipt is confirmed.";$("nextBtn").disabled=false};
$("csvBtn").onclick=()=>{let keys=Object.keys(responses[0]||{}),esc=v=>`"${String(v??"").replaceAll('"','""')}"`,csv=[keys.join(","),...responses.map(r=>keys.map(k=>esc(r[k])).join(","))].join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=`${sid}_${group}_responses.csv`;a.click()};
window.addEventListener("beforeunload",e=>{if(!finalized&&responses.length){e.preventDefault();e.returnValue=""}})})();
