(()=>{"use strict";const Q=new URLSearchParams(location.search),sid=(Q.get("id")||"").trim(),group=(Q.get("group")||"").trim().toUpperCase(),token=(Q.get("token")||"").trim(),valid=sid&&["A","B","C"].includes(group)&&token;let task=0,stage=0,responses=[],started=0,finalized=false;const $=x=>document.getElementById(x);$("studyMeta").textContent=STUDY_CONFIG.studyName;if(STUDY_CONFIG.requireAssignedLink&&!valid)$("invalid").hidden=false;else{$("consent").hidden=false;$("showId").textContent=sid;$("showGroup").textContent=group}
function sample(poly,n=61){let lens=[],cum=[0],tot=0;for(let i=0;i<poly.length;i++){let a=poly[i],b=poly[(i+1)%poly.length],l=Math.hypot(b[0]-a[0],b[1]-a[1]);lens.push(l);tot+=l;cum.push(tot)}let pts=[],ss=[];for(let k=0;k<n;k++){let s=tot*k/n,j=0;while(j<poly.length-1&&s>=cum[j+1])j++;let t=(s-cum[j])/lens[j],a=poly[j],b=poly[(j+1)%poly.length];pts.push([a[0]+t*(b[0]-a[0]),a[1]+t*(b[1]-a[1])]);ss.push(k/n)}return[pts,ss]}
function data(i){let p=STUDY_TASKS.polygons[i],r=STUDY_TASKS.refs[i],[pts,s]=sample(p),L=r[0],G=r[1],dl=pts.map(q=>Math.hypot(q[0]-L[0],q[1]-L[1])),dg=pts.map(q=>Math.hypot(q[0]-G[0],q[1]-G[1])),d1=a=>a.slice(1).map((v,k)=>v-a[k]),ad=a=>d1(a).map(Math.abs);return{s,dl,dg,d1l:d1(dl),d1g:d1(dg),cl:ad(d1(dl)),cg:ad(d1(dg))}}
function cc(){let c=$("plot"),x=c.getContext("2d");x.clearRect(0,0,c.width,c.height);x.font="17px system-ui";x.strokeStyle="#111";x.fillStyle="#111";return[c,x]}
function poly(p){let[c,x]=cc(),xs=p.map(q=>q[0]),ys=p.map(q=>q[1]),mnx=Math.min(...xs),mxx=Math.max(...xs),mny=Math.min(...ys),mxy=Math.max(...ys),X=v=>100+(v-mnx)/(mxx-mnx)*780,Y=v=>380-(v-mny)/(mxy-mny)*300;x.lineWidth=4;x.beginPath();p.forEach((q,i)=>i?x.lineTo(X(q[0]),Y(q[1])):x.moveTo(X(q[0]),Y(q[1])));x.closePath();x.stroke();for(const q of p){x.beginPath();x.arc(X(q[0]),Y(q[1]),5,0,2*Math.PI);x.fill()}}
function graph(a,b,l1,l2){let[c,x]=cc(),all=a.concat(b),lo0=Math.min(...all),hi0=Math.max(...all),pad=Math.max((hi0-lo0)*.08,.02),lo=lo0-pad,hi=hi0+pad,X=i=>90+i/(Math.max(a.length,b.length)-1)*820,Y=v=>390-(v-lo)/(hi-lo)*310;x.beginPath();x.moveTo(75,45);x.lineTo(75,390);x.lineTo(930,390);x.stroke();for(const f of [0,.25,.5,.75,1]){let xx=90+f*820;x.fillText(f.toFixed(2),xx-18,420)}function ln(v,d){x.setLineDash(d);x.beginPath();v.forEach((q,i)=>i?x.lineTo(X(i),Y(q)):x.moveTo(X(i),Y(q)));x.stroke()}ln(a,[]);ln(b,[12,9]);x.setLineDash([]);x.fillText(l1+" (solid)",755,35);x.fillText(l2+" (dashed)",755,58);x.fillText("normalized journey position s",365,455)}
function render(){let d=data(task);$("stageExtra").innerHTML="";if(group==="A"){$("heading").textContent=`Task A${task+1}`;$("instruction").textContent="Inspect the visible closed boundary.";poly(STUDY_TASKS.polygons[task])}else if(group==="B"){$("heading").textContent=`Task B${task+1}`;$("instruction").textContent="The boundary is hidden. Use only the two raw ordered distance histories.";graph(d.dl,d.dg,"D_L","D_G")}else{let n=["Raw distance histories","First changes","Change in the changes"];$("heading").textContent=`Task C${task+1} — Stage ${stage+1}: ${n[stage]}`;$("instruction").textContent="Record your current inference before continuing. Earlier responses cannot be edited.";stage===0?graph(d.dl,d.dg,"D_L","D_G"):stage===1?graph(d.d1l,d.d1g,"dD_L","dD_G"):graph(d.cl,d.cg,"C_L","C_G");if(stage===1)$("stageExtra").innerHTML='<label>Did you revise the previous inference?<select id="revised"><option value="">Select</option><option>Yes</option><option>No</option></select></label><label>If yes, what evidence caused the revision?<textarea id="revisionWhy"></textarea></label>';if(stage===2)$("stageExtra").innerHTML='<label>Most useful representation<select id="mostUseful"><option value="">Select</option><option>Raw distances</option><option>First changes</option><option>Change-in-change</option><option>Combination</option></select></label>'}let total=group==="C"?18:6,current=group==="C"?task*3+stage+1:task+1;$("progress").textContent=`Screen ${current} of ${total}`;started=performance.now();history.replaceState(null,"",location.href)}
function reset(){["ntrans","locs","nseg","evid"].forEach(id=>$(id).value="");$("conf").value="";$("status").textContent=""}
function validForm(){if(!$("ntrans").value.trim()||!$("nseg").value.trim()||!$("conf").value||!$("evid").value.trim()){$("status").textContent="Please complete transition count, segment count, confidence, and evidence.";return false}return true}
async function send(r){if(!STUDY_CONFIG.submitEndpoint)return;try{await fetch(STUDY_CONFIG.submitEndpoint,{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(r)})}catch(e){}}
$("startBtn").onclick=()=>{if(!$("ready").checked)return alert("Please confirm that you are ready.");$("consent").hidden=true;$("study").hidden=false;render()};
$("nextBtn").onclick=async()=>{if(finalized||!validForm())return;$("nextBtn").disabled=true;let r={study_id:sid,group,token,task:task+1,stage:group==="C"?stage+1:1,transitions:$("ntrans").value.trim(),locations:$("locs").value.trim(),segments:$("nseg").value.trim(),confidence:$("conf").value,evidence:$("evid").value.trim(),revised:$("revised")?.value||"",revision_why:$("revisionWhy")?.value.trim()||"",most_useful:$("mostUseful")?.value||"",stage_duration_ms:Math.round(performance.now()-started),submitted_at:new Date().toISOString(),user_agent:navigator.userAgent};responses.push(r);localStorage.setItem("study_"+token,JSON.stringify(responses));await send(r);reset();if(group==="C"&&stage<2){stage++;render();$("nextBtn").disabled=false;return}stage=0;task++;if(task<6){render();$("nextBtn").disabled=false;return}finalized=true;$("study").hidden=true;$("done").hidden=false;$("serverStatus").textContent=STUDY_CONFIG.submitEndpoint?"Responses were submitted during the study. Keep the CSV backup until receipt is confirmed.":"Central submission is not configured; download the CSV backup.";};
$("csvBtn").onclick=()=>{let keys=Object.keys(responses[0]||{}),esc=v=>`"${String(v??"").replaceAll('"','""')}"`,csv=[keys.join(","),...responses.map(r=>keys.map(k=>esc(r[k])).join(","))].join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=`${sid}_${group}_responses.csv`;a.click()};window.addEventListener("beforeunload",e=>{if(!finalized&&responses.length){e.preventDefault();e.returnValue=""}})})();